name: aspends_tracker
description: A simple yet powerful spend and income tracker app.
version: 5.1.0+6

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  hive: ^2.2.3
  pdf: ^3.10.4
  printing: ^5.11.1
  hive_flutter: ^1.1.0
  #material_color_utilities: ^0.8.0
  dynamic_color:
  zoom_tap_animation:
  flex_color_scheme:
  fl_chart: ^0.63.0
  local_auth: ^2.1.7
  home_widget: ^0.8.0
  excel: ^2.1.0
  stylish_bottom_bar: ^1.1.1
  path_provider: ^2.1.2
  google_fonts: ^6.2.0
  flutter_launcher_icons: ^0.13.1
  csv: ^5.0.2
  file_picker:
  permission_handler: ^11.3.0
  share_plus: ^7.2.1
  fluttertoast: ^8.2.12
  intl: ^0.20.2
  flutter_displaymode: ^0.6.0
  liquid_glass_renderer: ^0.1.1-dev.9
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
enable-impeller: true
flutter:
  uses-material-design: true

  assets:

  fonts:
    - family: NFont
      fonts:
        - asset: assets/font/RobotoSerif_36pt-Regular.ttf
    - family: Nunito
      fonts:
        - asset: assets/font/RobotoSerif_36pt-Regular.ttf

flutter_launcher_icons:
  android:
    generate: true
  ios: false
  adaptive_icon_background: "#FFFFFF"
  image_path: "assets/icons/icons8-morty-smith-150.png"


file_picker:
  android:
    enable: true
  ios:
    enable: false
  windows:
    enable: false
  linux:
    enable: false
